proxies:
  aws_bedrock:
    type: aws_bedrock
    endpoint: https://bedrock.us-east-1.amazonaws.com
    region: "os.environ/AWS_REGION"
    aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
    aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"

model_list:
  - model_name: claude-3-7-sonnet-v1
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: "us-west-2"
      aws_access_key_id: "os.environ/llm_AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/llm_AWS_SECRET_ACCESS_KEY"
      thinking: {"type": "enabled", "budget_tokens": 1024}
      stream: False
  - model_name: claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: "us-west-2"
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: "os.environ/AWS_REGION"
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
  - model_name: claude-3-opus
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0
      aws_region_name: us-west-2
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
  - model_name: claude-3-5-haiku
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
      aws_region_name: "os.environ/AWS_REGION"
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"

litellm_settings:
  drop_params: true
  set_verbose: true

general_settings:
  use_azure: false
  use_openai: false
